server {
    listen 80;
    index index.php index.html;
    root /var/www/html/public;

    # Los logs de acceso y errores se redirigen a stdout/stderr para que Docker los capture
    access_log /dev/stdout;
    error_log /dev/stderr;

    location / {
        # Intenta servir el archivo físico, si no existe redirige a index.php (Laravel)
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # OBLIGATORIO: Fuerza a pasar el HTTP_HOST original (incluyendo el puerto si existe).
        # Esto previene que Laravel asuma que estamos en el puerto 80 por defecto,
        # arreglando problemas de redirecciones en puertos no estándar (ej. 8000).
        fastcgi_param HTTP_HOST $http_host;
    }
}
