name: Deploy Frontend to Docker

on:
  push:
    branches:
      - features/equipo_ucv
  pull_request:
    branches:
      - features/equipo_ucv

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH_PROD }}
            git fetch origin ${{ vars.DEPLOY_BRANCH }}
            git checkout ${{ vars.DEPLOY_BRANCH }}
            git merge origin/${{ vars.DEPLOY_BRANCH }}
            cd ..
            docker compose -f docker-compose.prod.yml up -d --build ganaderasoft-frontend
